# Generated by Django 5.1.4 on 2025-01-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='suppliers',
            new_name='supplier',
        ),
    ]
