# Generated by Django 5.1.4 on 2025-01-14 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchased_products', '0001_initial'),
        ('suppliers', '0002_rename_suppliers_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedProducts',
            fields=[
                ('product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('piece_quantity', models.PositiveIntegerField()),
                ('profit_margin', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_products', to='purchased_products.category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_products', to='suppliers.supplier')),
            ],
        ),
    ]
