# Generated by Django 5.1.4 on 2025-01-14 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchased_products', '0003_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedproducts',
            old_name='product_ID',
            new_name='purchased_invoice',
        ),
        migrations.AddField(
            model_name='purchasedproducts',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_products', to='purchased_products.products'),
            preserve_default=False,
        ),
    ]
