# Generated by Django 5.1.4 on 2025-01-14 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchased_products', '0006_delete_productpricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='available_pieces',
        ),
        migrations.RemoveField(
            model_name='purchasedproducts',
            name='profit_margin',
        ),
    ]
