# Generated by Django 5.1.4 on 2025-01-14 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchased_products', '0007_remove_products_available_pieces_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('profit_margin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchased_products.products')),
            ],
        ),
    ]
