# Generated by Django 5.1.4 on 2025-01-14 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchased_products', '0010_products_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpricing',
            name='category',
        ),
    ]
