# Generated by Django 5.1.4 on 2025-01-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchased_products', '0014_productpricing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpricing',
            name='category',
        ),
    ]
