# Generated by Django 5.1.4 on 2025-01-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchased_products', '0015_remove_productpricing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
