# Generated by Django 5.1.4 on 2025-01-16 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchased_products', '0016_alter_products_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedproducts',
            old_name='product_id',
            new_name='product',
        ),
    ]
