# Generated by Django 5.1.4 on 2025-01-16 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchased_products', '0017_rename_product_id_purchasedproducts_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedproducts',
            name='category',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_products', to='purchased_products.category'),
        ),
        migrations.AlterField(
            model_name='purchasedproducts',
            name='product_name',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_stock', models.PositiveIntegerField()),
                ('current_sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchased_products.products')),
            ],
        ),
    ]
