# Generated by Django 5.1.4 on 2025-01-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchased_products', '0018_alter_purchasedproducts_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricing',
            name='category_id',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productpricing',
            name='category_name',
            field=models.CharField(default=1, editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
