# Generated by Django 5.1.4 on 2025-01-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchased_products', '0019_productpricing_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='category_id',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='category_name',
            field=models.CharField(default=1, editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
