# Generated by Django 5.1.4 on 2025-01-27 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchased_products', '0021_stock_product_name'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='productpricing',
        #     name='is_current',
        #     field=models.BooleanField(default=False),
        # ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sale_id', models.CharField(max_length=10)),
                ('product_name', models.CharField(editable=False, max_length=255)),
                ('category_id', models.IntegerField(editable=False)),
                ('category_name', models.CharField(editable=False, max_length=255)),
                ('current_sell_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Online', 'Online')], default='Cash', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchased_products.products')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]

