# Generated by Django 5.1.4 on 2025-01-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchased_products', '0022_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricing',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
