# Generated by Django 5.1.4 on 2025-01-27 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchased_products', '0022_productpricing_is_current_sale'),
        ('purchased_products', '0023_productpricing_is_current'),
    ]

    operations = [
    ]
