# Generated by Django 5.1.4 on 2025-01-28 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchased_products', '0023_alter_sale_options_productpricing_is_current_and_more'),
        ('purchased_products', '0026_sale_created_at'),
    ]

    operations = [
    ]
