# Generated by Django 5.1.4 on 2025-01-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchased_products', '0028_alter_sale_options_alter_sale_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_id',
            field=models.CharField(max_length=16),
        ),
    ]
