# Generated by Django 5.1.4 on 2025-01-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchased_products', '0030_returnsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnsale',
            name='return_sale_id',
            field=models.CharField(editable=False, max_length=16, unique=True),
        ),
    ]
