# Generated by Django 5.1.4 on 2025-01-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchased_products', '0031_alter_returnsale_return_sale_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Dashboard', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Dashboard Analytics',
            },
        ),
    ]
