# Generated by Django 5.1.4 on 2025-02-12 06:31

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('purchased_products', '0032_dashboardanalytics'),  # adjust this to your latest migration
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]